# Generated by Django 4.0.4 on 2022-06-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades_eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_evento', models.CharField(max_length=50)),
                ('Fecha', models.DateTimeField()),
                ('Convoca', models.CharField(max_length=50)),
                ('Participan', models.IntegerField()),
                ('Institucion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Investigadorxs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Titulo', models.CharField(max_length=50)),
                ('Pertenencia_institucional', models.CharField(max_length=50)),
                ('Edad', models.IntegerField()),
                ('email', models.EmailField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Título', models.CharField(max_length=50)),
                ('Autorxs', models.CharField(max_length=50)),
                ('Pertenencia_institucional_de_autorxs', models.CharField(max_length=50)),
                ('url_de_la_publicacion', models.URLField()),
            ],
        ),
    ]
